---
dist: trusty
cache: apt
language: ruby
rvm: 2.2.1
install:
- sudo apt-get update
- sudo apt-get install -y apt-transport-https ca-certificates
- sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
- echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
- sudo apt-get update
- sudo apt-get -o dpkg::options::="--force-confnew" install -y docker-engine=1.9.1-0~trusty
- echo "docker-engine hold" | sudo dpkg --set-selections
- git clone https://github.com/flant/thepackager ~/thepackager
- echo "export BUNDLE_GEMFILE=~/thepackager/Gemfile" | tee -a ~/.bashrc
- export BUNDLE_GEMFILE=~/thepackager/Gemfile
- gem install bundler
- bundle install
script: thepackager build
sudo: required
before_script: thepackager prepare
deploy:
  provider: script
  script: thepackager deploy
  'on':
    tags: true
env:
- THEPACKAGER_TARGET=ubuntu
- THEPACKAGER_TARGET=ubuntu-12.04
- THEPACKAGER_TARGET=centos
- THEPACKAGER_TARGET=centos-centos6
