---
dist: trusty
cache: apt
language: ruby
rvm: 2.2.1
install:
- sudo apt-get update
- sudo apt-get install -y apt-transport-https ca-certificates
- sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
- echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
- sudo apt-get update
- sudo apt-get -o dpkg::options::="--force-confnew" install -y --force-yes docker-engine=1.9.1-0~trusty
- echo "docker-engine hold" | sudo dpkg --set-selections
- git clone https://github.com/flant/buildizer ~/buildizer
- echo 'export BUNDLE_GEMFILE=~/buildizer/Gemfile' | tee -a ~/.bashrc
- export BUNDLE_GEMFILE=~/buildizer/Gemfile
- gem install bundler
- gem install overcommit
- bundle install
script: buildizer build && buildizer test
sudo: required
before_script: buildizer prepare
env:
- BUNDLE_GEMFILE=~/buildizer/Gemfile BUILDIZER_TARGET=ubuntu/14.04
- BUNDLE_GEMFILE=~/buildizer/Gemfile BUILDIZER_TARGET=ubuntu/12.04
- BUNDLE_GEMFILE=~/buildizer/Gemfile BUILDIZER_TARGET=centos/centos7
after_success: buildizer deploy
